using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PdaRngUiFragment : BoxContainer
{
    public Action? OnPrintPressed;

    public PdaRngUiFragment()
    {
        RobustXamlLoader.Load(this);
        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void UpdateState(bool hasRolled)
    {
        PrintButton.Disabled = hasRolled;
        StatusLabel.Text = Loc.GetString(hasRolled
            ? "pda-rng-ui-status-rolled"
            : "pda-rng-ui-status-ready");
    }
}
